---
  - name: create pid file for mysql
    ansible.builtin.file:
      path: /var/run/mysqld/mysqld.pid
      owner: mysql
      group: mysql
      state: touch
    when: ansible_hostname in [var_group.percona_node_02_short_name,var_group.percona_node_03_short_name]

  - name: MYSQL | ensure mysql service is started
    become: true
    shell: systemctl start mysql
    async: 300
    poll: 5
    when: ansible_hostname in [var_group.percona_node_02_short_name,var_group.percona_node_03_short_name]